name: genron
recipe: drupal9
config:
  webroot: web
#   xdebug: true
#   config:
#     php: .vscode/php.ini

env_file:
  - .env

services:
  appserver:
    type: php:8.1
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin
