_core:
  default_config_hash: t7clj3mzmOGrXX0HuCH5usf0vEqRtnMTBFVBIEmZ5pc
langcode: ja
first_day: 0
country:
  default: JP
timezone:
  default: Asia/Tokyo
  user:
    configurable: true
    default: 0
    warn: false
