_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: ja
uuid: 97bb6b75-7672-4a86-b25d-2e96635d4a45
name: ゲンロンΩ（非公式）
mail: admin@localhost
slogan: ''
page:
  403: ''
  404: ''
  front: /node/14
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
